// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://injzxitxnzxeopafexng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imluanp4aXR4bnp4ZW9wYWZleG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0OTY4ODYsImV4cCI6MjA5MDA3Mjg4Nn0.UomvQIou9URyR6FLjYBnmWBMhIxvEzFcTY1qXGt98iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});